TwoDEngine: PythonBinding Class Reference
PythonBinding Class Reference
#include <PythonBinding.h>
Public Member Functions
PythonBinding ()
~PythonBinding ()
bool isInitialized () const
bool runScript (const std::string &script)
bool runScriptFile (const std::string &filename)
void registerFunction (const std::string &name, std::function< void()> func)
bool callFunction (const std::string &name)
void setInt (const std::string &name, int value)
int getInt (const std::string &name, int defaultValue=0)
void setFloat (const std::string &name, float value)
float getFloat (const std::string &name, float defaultValue=0.0f)
void setString (const std::string &name, const std::string &value)
std::string getString (const std::string &name, const std::string &defaultValue="")
void setBool (const std::string &name, bool value)
bool getBool (const std::string &name, bool defaultValue=false)
Detailed Description
Definition at line 10 of file PythonBinding.h.
Constructor & Destructor Documentation
PythonBinding()
PythonBinding::PythonBinding () inline
Definition at line 20 of file PythonBinding.h.
~PythonBinding()
PythonBinding::~PythonBinding () inline
Definition at line 33 of file PythonBinding.h.
Member Function Documentation
callFunction()
bool PythonBinding::callFunction (const std::string & name) inline
Definition at line 128 of file PythonBinding.h.
getBool()
bool PythonBinding::getBool (const std::string & name, bool defaultValue = false) inline
Definition at line 196 of file PythonBinding.h.
getFloat()
float PythonBinding::getFloat (const std::string & name, float defaultValue = 0.0f) inline
Definition at line 166 of file PythonBinding.h.
getInt()
int PythonBinding::getInt (const std::string & name, int defaultValue = 0) inline
Definition at line 149 of file PythonBinding.h.
Referenced by runScriptFile().
getString()
std::string PythonBinding::getString (const std::string & name, const std::string & defaultValue = "") inline
Definition at line 182 of file PythonBinding.h.
isInitialized()
bool PythonBinding::isInitialized () const inline
Definition at line 40 of file PythonBinding.h.
registerFunction()
void PythonBinding::registerFunction (const std::string & name, std::function< void()> func) inline
Definition at line 122 of file PythonBinding.h.
runScript()
bool PythonBinding::runScript (const std::string & script) inline
Definition at line 45 of file PythonBinding.h.
runScriptFile()
bool PythonBinding::runScriptFile (const std::string & filename) inline
Definition at line 59 of file PythonBinding.h.
References getInt(), setBool(), setFloat(), and setInt().
setBool()
void PythonBinding::setBool (const std::string & name, bool value) inline
Definition at line 191 of file PythonBinding.h.
Referenced by runScriptFile().
setFloat()
void PythonBinding::setFloat (const std::string & name, float value) inline
Definition at line 160 of file PythonBinding.h.
Referenced by runScriptFile().
setInt()
void PythonBinding::setInt (const std::string & name, int value) inline
Definition at line 143 of file PythonBinding.h.
Referenced by runScriptFile().
setString()
void PythonBinding::setString (const std::string & name, const std::string & value) inline
Definition at line 177 of file PythonBinding.h.
The documentation for this class was generated from the following file:
libs/python/PythonBinding.h