TwoDEngine: Game Class Reference
Game Class Reference
Main game engine class that manages the game lifecycle.
#include <Game.h>
Public Member Functions
Game ()
Default constructor.
~Game ()
Destructor.
void Initialize ()
Initialize the game engine and all subsystems.
void Run ()
Execute the main game loop.
void ProcessInput ()
Process all input events from the user.
void Update ()
Update the game state based on elapsed time.
void Render ()
Render the current game state to the screen.
void Destroy ()
Clean up and destroy all game resources.
Detailed Description
Main game engine class that manages the game lifecycle.
The Game class encapsulates all core game functionality including:
SDL initialization and window management
Main game loop execution
Input event processing
Game state updates
Frame rendering
Resource cleanup
Usage Example
int main(int argc, char* argv[])
{
    Game game;
    game.Initialize();
    game.Run();
    game.Destroy();
    return 0;
}
Note
This class follows the game loop pattern with distinct phases: Input → Update → Render
Definition at line 42 of file Game.h.
Constructor & Destructor Documentation
Game()
Game::Game ()
Default constructor.
Constructs a new Game object and initializes member variables to their default states. Does not perform SDL initialization - call Initialize() for that.
See also
Initialize()
Definition at line 6 of file Game.cpp.
~Game()
Game::~Game ()
Destructor.
Destroys the Game object and ensures all resources are properly cleaned up. If Destroy() has not been called, it will be called automatically.
See also
Destroy()
Definition at line 12 of file Game.cpp.
Member Function Documentation
Destroy()
void Game::Destroy ()
Clean up and destroy all game resources.
Performs cleanup in the following order:
Destroys game-specific resources (textures, sounds, entities)
Cleans up ImGui context
Destroys SDL renderer
Destroys SDL window
Closes audio system
Quits SDL extensions (TTF, IMG, Mixer)
Quits SDL
Note
Should be called before the Game object is destroyed
Safe to call multiple times (subsequent calls are no-ops)
Warning
Not calling this may cause resource leaks
See also
Initialize()
Definition at line 43 of file Game.cpp.
Referenced by main().
Initialize()
void Game::Initialize ()
Initialize the game engine and all subsystems.
Performs the following initialization steps:
Initializes SDL and its extensions (SDL_image, SDL_ttf, SDL_mixer)
Creates the game window
Creates the hardware-accelerated renderer
Initializes ImGui for debug UI
Loads initial game assets
Sets up the initial game state
Returns
void (Consider changing to bool for error handling)
Note
Must be called before Run()
Warning
Calling this multiple times without calling Destroy() first may cause resource leaks
See also
Destroy()
Todo
Change return type to bool to indicate success/failure
Add error logging for initialization failures
Definition at line 17 of file Game.cpp.
Referenced by main().
ProcessInput()
void Game::ProcessInput ()
Process all input events from the user.
Polls and handles SDL events including:
Keyboard input (key press/release)
Mouse input (button press/release, motion, wheel)
Window events (close, resize, focus)
Game controller input
This method is called once per frame by Run() and updates the internal input state that can be queried during Update().
Note
ImGui events are processed first to allow UI interaction
Input state is accumulated and can be queried in Update()
See also
Run()
Update()
Definition at line 28 of file Game.cpp.
Render()
void Game::Render ()
Render the current game state to the screen.
Performs the following rendering steps:
Clears the screen with background color
Renders game background
Renders all game entities (sprites, text, shapes)
Renders UI elements
Renders debug information (ImGui)
Presents the final frame to the screen
Rendering order is important for proper layering (back to front).
Note
Called once per frame by Run()
Uses double buffering - changes are not visible until SDL_RenderPresent()
See also
Run()
Update()
Definition at line 38 of file Game.cpp.
Run()
void Game::Run ()
Execute the main game loop.
Runs the game loop until the user quits. Each iteration of the loop:
Calculates delta time since last frame
Processes input events via ProcessInput()
Updates game state via Update()
Renders the frame via Render()
Limits frame rate to target FPS
The loop continues until a quit event is received (e.g., window close, ESC key, or programmatic quit request).
Note
This is a blocking call that returns only when the game exits
Frame rate is typically capped at 60 FPS
See also
ProcessInput()
Update()
Render()
Definition at line 23 of file Game.cpp.
Referenced by main().
Update()
void Game::Update ()
Update the game state based on elapsed time.
Updates all game logic including:
Entity positions and velocities
Animation states
Collision detection and response
AI behavior
Physics simulation
Script execution (Lua/Python)
Audio playback
All updates should be frame-rate independent by using delta time.
Note
Called once per frame by Run()
All movement and time-based changes should use delta time
See also
Run()
Render()
Todo
Add deltaTime parameter for frame-rate independence
Definition at line 33 of file Game.cpp.
The documentation for this class was generated from the following files:
src/Game.h
src/Game.cpp